background #212121
foreground #c3f884

selection_foreground #000000
selection_background #f2ab3f

cursor #f187a8

color0 #242426
color8 #636667
#: black

color1 #e95485
color9 #f187a8
#: red

color2  #bde25a
color10 #cfec82
#: green

color3  #f2ab3f
color11 #e8e092
#: yellow

color4  #90d4e0
color12 #90d4e0
#: blue

color5  #a98bf7
color13 #a98bf7
#: magenta

color6  #748386
color14 #b6c5ca
#: cyan

color7  #d6d6d6
color15 #f9f9f9
#: white

